server:
  port: 9000 # Puerto único para el gateway

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: shows-service
          uri: lb://showsService
          predicates:
            - Path=/v1/shows/**

        - id: ticket-purchase-service
          uri: lb://ticketPurchaseService
          predicates:
            - Path=/v1/tickets/**

        - id: seat-booking-service
          uri: lb://seatBookingService
          predicates:
            - Path=
              /v1/seats/**,
              /v1/reservations/**

        - id: promotion-service
          uri: lb://promotionService
          predicates:
            - Path=/v1/promotions/**

    inetutils:
      preferred-networks:
        - 10.207.* # o tu rango de IP local

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always