openapi: '3.0.3'
info:
  title: Email Notification Service API
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /v1/notifications/emails:
    get:
      tags:
        - Email Notifications
      summary: Get all email notifications
      responses:
        '200':
          description: List of all email notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EmailNotification'
    post:
      tags:
        - Email Notifications
      summary: Send a new email notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailNotificationRequest'
      responses:
        '201':
          description: Email notification sent
  /v1/notifications/emails/{id}:
    get:
      tags:
        - Email Notifications
      summary: Get an email notification by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Email notification details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailNotification'
        '404':
          description: Email notification not found
    delete:
      tags:
        - Email Notifications
      summary: Delete an email notification by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Email notification deleted
        '404':
          description: Email notification not found
components:
  schemas:
    EmailNotification:
      type: object
      properties:
        id:
          type: string
          description: Unique ID of the email notification
        recipient:
          type: string
          format: email
          description: Email address of the recipient
        subject:
          type: string
          description: Subject of the email
        body:
          type: string
          description: Body content of the email
        status:
          type: string
          description: Status of the email notification
          enum:
            - sent
            - failed
            - pending
        createdAt:
          type: string
          format: date-time
          description: Creation date
    EmailNotificationRequest:
      type: object
      properties:
        recipient:
          type: string
          format: email
          description: Email address of the recipient
        subject:
          type: string
          description: Subject of the email
        body:
          type: string
          description: Body content of the email