
@startuml SequenceDiagram

participant "Frontend" as FE
participant "Shows Service" as ShowsService
participant "Seat Booking Service" as SeatBookingService
participant "Ticket Purchase Service" as TicketPurchaseService
participant "Payment Service" as PaymentService
participant "Promotion Service" as PromotionService
participant "Message Queue" as MQ

' El Scheduler ejecuta esta tarea automáticamente cada minuto
note right of SeatBookingService
  Scheduled task executed every minute
end note
SeatBookingService -> SeatBookingService: Update reservations to EXPIRED\nUpdate seat status to AVAILABLE

' Flujo: Cliente visualiza horarios de programas
FE -> ShowsService: Get shows
ShowsService --> FE: Return shows
FE -> ShowsService: Get showtimes for specific show
ShowsService --> FE: Return showtimes

' Flujo: Cliente selecciona asiento
FE -> SeatBookingService: Get seats
SeatBookingService --> FE: Return seats

' Flujo: Cliente selecciona compra ticket
FE -> SeatBookingService: Reserve seats
SeatBookingService -> SeatBookingService: Create reservation\nSet seat status UNAVAILABLE
SeatBookingService --> FE : Seats reserved
FE -> TicketPurchaseService: Purchase ticket
TicketPurchaseService -> PromotionService: Apply promotion
PromotionService -> PromotionService: Process promotion
PromotionService --> TicketPurchaseService: Promotion applied
TicketPurchaseService -> SeatBookingService: Get seat status 
SeatBookingService --> TicketPurchaseService: Seat status (AVAILABLE/UNAVAILABLE)
TicketPurchaseService -> TicketPurchaseService: Create ticket if seat AVAILABLE


TicketPurchaseService -[#green]-> MQ: Produce ticketCreated with final price

' Procesamiento del pago
MQ -[#green]-> PaymentService: Consume ticketCreated
PaymentService -> PaymentService: Process payment
PaymentService -[#green]-> MQ: Produce ticketPaid (PAID/FAILED)

' Flujo: Actualización de asientos
MQ -[#green]-> SeatBookingService: Consume ticketCreated
MQ -[#green]-> SeatBookingService: Consume ticketPaid
SeatBookingService -> SeatBookingService: Update reservation status (COMPLETED)

@enduml