openapi: '3.0.3'
info:
  title: Cinema Promotion Service API
  version: '1.0'
servers:
  - url: https://api.server.test/v1
tags:
  - name: Promotions Management
    description: Promotion management for cinema tickets
  - name: Apply Promotions
    description: Apply promotions to tickets or purchases
paths:
  /v1/promotions:
    get:
      tags:
        - Promotions Management
      summary: Get all promotions
      description: Retrieve a list of all active promotions.
      responses:
        '200':
          description: List of all promotions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PromotionResponse'

  /v1/promotions/apply:
    post:
      tags:
        - Apply Promotions 
      summary: Apply a promotion
      description: Apply a promotion to a specific ticket or purchase.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplyPromotionRequest'
      responses:
        '200':
          description: Promotion applied successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplyPromotionResponse'
        '400':
          description: Invalid promotion request
        '404':
          description: Promotion not found

components:
  schemas:
    PromotionResponse:
      type: object
      properties:
        promotionId:
          type: string
          format: uuid
          description: Unique ID of the promotion
        name:
          type: string
          description: Name of the promotion
        description:
          type: string
          description: Description of the promotion
        discountPercentage:
          type: number
          format: float
          description: Discount percentage offered by the promotion
        validFrom:
          type: string
          format: date-time
          description: Start date of the promotion
        validUntil:
          type: string
          format: date-time
          description: End date of the promotion

    ApplyPromotionRequest:
      type: object
      properties:
        ticketId:
          type: string
          format: uuid
          description: Unique ID of the ticket to which the promotion will be applied
        promotionId:
          type: string
          format: uuid
          description: Unique ID of the promotion to apply
        ticketPrice:
          type: number
          format: float
          description: Price of the ticket
      required:
        - ticketId
        - ticketPrice

    ApplyPromotionResponse:
      type: object
      properties:
        ticketId:
          type: string
          description: ID of the ticket the promotion was applied to
        finalPrice:
          type: number
          format: float
          description: Final price of the ticket after applying the promotion