openapi: '3.0.3'
info:
  title: Cinema Seat Management API
  version: '1.0'
servers:
  - url: https://api.server.test/v1
tags:
  - name: Cinema Seats
    description: Seat management for cinema rooms
  - name: Seat Reservation
    description: Reserve seats for shows
  - name: Reservation Update
    description: Update reservation statuses
paths:
  /v1/seats:
    get:
      tags:
        - Cinema Seats
      summary: Get all seats or search for specific seats
      description: Retrieve a list of all seats in the cinema or search for specific seats by row, and number.
      responses:
        '200':
          description: List of filtered seats or specific seat details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SeatResponse'
        '404':
          description: Seat not found
        '500':
          description: Internal server error

  /v1/seats/{seatId}:
    get:
      tags:
        - Cinema Seats
      summary: Get a seat by ID
      description: Retrieve details of a specific seat by its ID.
      parameters:
        - name: seatId
          in: path
          required: true
          description: ID of the seat to retrieve.
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Seat details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SeatResponse'
        '404':
          description: Seat not found
        '500':
          description: Internal server error
    delete:
      tags:
        - Cinema Seats
      summary: Deactivate a seat by ID
      description: Mark a specific seat as inactive instead of deleting it.
      parameters:
        - name: seatId
          in: path
          required: true
          description: ID of the seat to deactivate.
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Seat deactivated successfully
        '404':
          description: Seat not found
        '500':
          description: Internal server error

  /v1/seats/reserve:
    post:
      tags:
        - Seat Reservation
      summary: Reserve seats temporarily
      description: Reserve one or more seats for a specific show for a limited time.
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/ReservationRequest'
      responses:
        '200':
          description: Seats reserved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservationResponse'
        '400':
          description: Invalid input
        '404':
          description: One or more seats not found
        '409':
          description: One or more seats are already reserved or occupied
        '500':
          description: Internal server error

  /v1/reservations/update:
    post:
      tags:
        - Reservation Update
      summary: Update the status of Reservation
      description: Update the status of reservations and return their IDs and statuses.
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/UpdateRequest'
      responses:
        '200':
          description: Updated reservation statuses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateResponse'
        '400':
          description: Invalid input
        '404':
          description: One or more reservations not found
        '500':
          description: Internal server error

components:
  schemas:
    SeatResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique ID of the seat
        row:
          type: string
          description: Row of the seat
        number:
          type: integer
          description: Seat number
        status:
          type: string
          description: Status of the seat
          enum:
            - AVAILABLE
            - UNAVAILABLE
        isActive:
          type: boolean
          description: Indicates if the seat is active or deactivated
      required:
        - id
        - row
        - number
        - status
        
    ReservationRequest:
      type: object
      properties:
        seatIds:
          type: array
          items:
            type: string
            format: uuid
          description: List of seat IDs to reserve
        showId:
          type: string
          format: uuid
          description: ID of the show the seats are reserved for
        showtimeId:
          type: string
          format: uuid
          description: ID of the showtime for the reservation
        reservedBy:
          type: string
          description: Name of the user who made the reservation
      required:
        - seatIds
        - showId
        - showtimeId
        - reservedBy

    ReservationResponse:
      type: object
      properties:
        reservationId:
          type: string
          format: uuid
          description: Unique ID of the reservation
        seats:
          type: array
          items:
            type: string
          description: List of seats that were successfully reserved, shows their row and number
        reservedBy:
          type: string
          description: Name of the user who made the reservation
        reservationExpiresAt:
          type: string
          format: Instant
          description: Expiration time for the reservation
        status:
          type: string
          description: Estado de la reserva
          enum:
            - ACTIVE
            - EXPIRED
            - COMPLETED
      required:
        - seats
        - reservedBy
        - showTitle
        - showtime
        - status

    UpdateRequest:
      type: object
      properties:
        reservationId:
          type: string
          format: uuid
          description: Reservation ID to update
      required:
        - reservationId

    UpdateResponse:
      type: object
      properties:
        reservationId:
          type: string
          format: uuid
          description: Updated reservation ID
        reservationStatuses:
          type: string
          description: Updated reservation status
      required:
        - reservationId
        - reservationStatus