version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: showsServicedb
      DEFAULT_ENCODING: UTF-8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: