@startuml SequenceDiagram

actor Client
participant "Frontend" as FE
participant "Shows Service" as ShowsService
participant "Seat Booking Service" as SeatBookingService
participant "Ticket Purchase Service" as TicketPurchaseService
participant "Payment Service" as PaymentService
participant "Notification Service" as NotificationService
participant "Promotion Service" as PromotionService
participant "Message Queue" as MQ

' Flujo: Cliente visualiza horarios de programas
Client -> FE: Request Showtimes
FE -> ShowsService: Get Showtimes
ShowsService --> FE: Return Showtimes

' Flujo: Cliente selecciona asiento y compra ticket
Client -> FE: Select Seat and Purchase Ticket
FE -> SeatBookingService: Book seats
SeatBookingService --> SeatBookingService: Update seats status
SeatBookingService --> FE : Seats Booked
FE -> TicketPurchaseService: Purchase Ticket (with Promotion ?)
TicketPurchaseService -[#blue]-> PromotionService: Validate Promotion (Synchronous)
PromotionService --> TicketPurchaseService: Promotion Validated
TicketPurchaseService --> TicketPurchaseService: Create Ticket(s) Purchase with Promotion applied
TicketPurchaseService -[#green]-> MQ: Publish TicketCreated with final price

' Procesamiento del pago
MQ -[#green]-> PaymentService: Consume TicketCreated
PaymentService --> PaymentService: Process Payment (pending/completed/failed)
PaymentService -[#green]-> MQ: Publish PaymentProcessed

' Actualización del estado del ticket
MQ -[#green]-> TicketPurchaseService: Consume PaymentProcessed
TicketPurchaseService --> TicketPurchaseService: Update Ticket Status (pending/purchased/canceled)
TicketPurchaseService -[#green]-> MQ: Publish Ticket (Status Updated)

' Notificación al cliente
MQ -[#green]-> NotificationService: Consume PaymentProcessed
NotificationService --> Client: Send Payment Notification

' Flujo: Actualización de asientos
MQ -[#green]-> SeatBookingService: Consume Ticket (Status Updated)
SeatBookingService --> SeatBookingService: Update Seat Status (avaible/reserved/occupied)
SeatBookingService -[#green]-> MQ: Publish Seat Status Updated

@enduml