openapi: '3.0.3'
info:
  title: Cinema Seat Management API
  version: '1.0'
servers:
  - url: https://api.server.test/v1
tags:
  - name: Cinema Seats
    description: Seat management for cinema rooms
paths:
  /v1/seats:
    get:
      tags:
        - Cinema Seats
      summary: Get all seats or search for specific seats
      description: Retrieve a list of all seats in the cinema or search for specific seats by room, row, and number.
      parameters:
        - name: room
          in: query
          required: true  # Room is now required
          description: Filter by room or search for a specific room.
          schema:
            type: string
        - name: status
          in: query
          description: Filter by seat status (e.g., available, reserved, occupied).
          schema:
            type: string
        - name: row
          in: query
          description: Filter by row or search for a specific row.
          schema:
            type: string
        - name: number
          in: query
          description: Search for a specific seat by number.
          schema:
            type: integer
      responses:
        '200':
          description: List of filtered seats or specific seat details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Seat'
        '404':
          description: Seat not found
        '500':
          description: Internal server error

  /v1/seats/{id}:
    get:
      tags:
        - Cinema Seats
      summary: Get a seat by ID
      description: Retrieve details of a specific seat by its ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the seat to retrieve.
          schema:
            type: string
      responses:
        '200':
          description: Seat details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SeatResponse'
        '404':
          description: Seat not found
        '500':
          description: Internal server error
    delete:
      tags:
        - Cinema Seats
      summary: Deactivate a seat by ID
      description: Mark a specific seat as inactive instead of deleting it.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the seat to deactivate.
          schema:
            type: string
      responses:
        '204':
          description: Seat deactivated successfully
        '404':
          description: Seat not found
        '500':
          description: Internal server error

components:
  schemas:
    Seat:
      type: object
      properties:
        id:
          type: string
          description: Unique ID of the seat
        room:
          type: string
          description: Room where the seat is located
        row:
          type: string
          description: Row of the seat
        number:
          type: integer
          description: Seat number
        status:
          type: string
          description: Status of the seat
          enum:
            - available
            - reserved
            - occupied
        isActive:
          type: boolean
          description: Indicates if the seat is active or deactivated

    SeatResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique ID of the seat
        room:
          type: string
          description: Room where the seat is located
        row:
          type: string
          description: Row of the seat
        number:
          type: integer
          description: Seat number
        status:
          type: string
          description: Status of the seat
          enum:
            - available
            - reserved
            - occupied
        isActive:
          type: boolean
          description: Indicates if the seat is active or deactivated