server:
  port: 8080

spring:
  config:
    activate:
      on-profile: default
  application:
    name: showsService

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/showsServicedb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  h2:
#    console:
#      enabled: true
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:showsServicedb
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher